
export const nonEmptyString={type:'string',minLength:1};
const evidence={type:'object',additionalProperties:false,required:['title','description','confidence','sourceIds'],properties:{title:nonEmptyString,description:nonEmptyString,confidence:{type:'string',enum:['verified','developing','hypothesis']},sourceIds:{type:'array',minItems:1,maxItems:6,items:nonEmptyString}}};
export const localizedPageSchema={type:'object',additionalProperties:false,required:['cover','question','signals','pattern','insight','observe'],properties:{
cover:{type:'object',additionalProperties:false,required:['eyebrow','secondaryEyebrow','title','summary'],properties:{eyebrow:nonEmptyString,secondaryEyebrow:nonEmptyString,title:nonEmptyString,summary:nonEmptyString}},
question:{type:'object',additionalProperties:false,required:['lead','title','footnote'],properties:{lead:nonEmptyString,title:nonEmptyString,footnote:nonEmptyString}},
signals:{type:'object',additionalProperties:false,required:['title','sourceNote','items'],properties:{title:nonEmptyString,sourceNote:nonEmptyString,items:{type:'array',minItems:2,maxItems:4,items:{type:'object',additionalProperties:false,required:['label','title','body','whyImportant','evidence'],properties:{label:nonEmptyString,title:nonEmptyString,body:nonEmptyString,whyImportant:nonEmptyString,evidence}}}}},
pattern:{type:'object',additionalProperties:false,required:['title','before','shift','now','conclusion'],properties:{title:nonEmptyString,before:nonEmptyString,shift:nonEmptyString,now:nonEmptyString,conclusion:nonEmptyString}},
insight:{type:'object',additionalProperties:false,required:['title','formula','explanation'],properties:{title:nonEmptyString,formula:nonEmptyString,explanation:nonEmptyString}},
observe:{type:'object',additionalProperties:false,required:['title','items','ending'],properties:{title:nonEmptyString,items:{type:'array',minItems:3,maxItems:4,items:{type:'object',additionalProperties:false,required:['label','prompt','meta'],properties:{label:nonEmptyString,prompt:nonEmptyString,meta:nonEmptyString}}},ending:nonEmptyString}}
}};
export const dailyCopySchema={type:'object',additionalProperties:false,required:['label','decisionTitle','decisionSummary','thresholdReason','observeNext'],properties:{label:nonEmptyString,decisionTitle:nonEmptyString,decisionSummary:nonEmptyString,thresholdReason:nonEmptyString,observeNext:{type:'array',minItems:2,maxItems:4,items:nonEmptyString}}};
export const evolutionCopySchema={type:'object',additionalProperties:false,required:['title','description','implication'],properties:{title:nonEmptyString,description:nonEmptyString,implication:nonEmptyString}};
export const baseStageSchema={type:'object',additionalProperties:false,required:['insightId','slug','parentInsightId','previousInsightId','en','dailyStateEn','processStage','processContentEn','nextQuestionEn','observeNextEn'],properties:{insightId:{type:['string','null']},slug:nonEmptyString,parentInsightId:{type:['string','null']},previousInsightId:{type:['string','null']},en:localizedPageSchema,dailyStateEn:dailyCopySchema,processStage:{type:'string',enum:['signal','emerging','accelerating','structural','maturing','uncertain','declining']},processContentEn:evolutionCopySchema,nextQuestionEn:nonEmptyString,observeNextEn:{type:'array',minItems:3,maxItems:4,items:nonEmptyString}}};
export const translationStageSchema={type:'object',additionalProperties:false,required:['page','dailyState','processContent','nextQuestion','observeNext'],properties:{page:localizedPageSchema,dailyState:dailyCopySchema,processContent:evolutionCopySchema,nextQuestion:nonEmptyString,observeNext:{type:'array',minItems:3,maxItems:4,items:nonEmptyString}}};
const P=new Set(['无字段','没有字段','沒有欄位','待补充','待補充','暂无内容','暫無內容','no field','no fields','missing field','not available','n/a','未入力','項目なし','フィールドなし']);
const meaningful=v=>typeof v==='string'&&v.trim()&&!P.has(v.trim().toLowerCase());
export function validatePage(page,lang){const m=[];for(const [f,v] of [['cover.title',page?.cover?.title],['cover.summary',page?.cover?.summary],['question.lead',page?.question?.lead],['question.title',page?.question?.title],['signals.title',page?.signals?.title],['pattern.title',page?.pattern?.title],['pattern.before',page?.pattern?.before],['pattern.shift',page?.pattern?.shift],['pattern.now',page?.pattern?.now],['pattern.conclusion',page?.pattern?.conclusion],['insight.title',page?.insight?.title],['insight.explanation',page?.insight?.explanation],['observe.title',page?.observe?.title],['observe.ending',page?.observe?.ending]])if(!meaningful(v))m.push(`${lang}.${f}`);if(!Array.isArray(page?.signals?.items)||page.signals.items.length<2)m.push(`${lang}.signals.items`);if(!Array.isArray(page?.observe?.items)||page.observe.items.length<3)m.push(`${lang}.observe.items`);if(m.length){const e=new Error(`Staged Writer produced incomplete ${lang} content: ${m.join(', ')}`);e.status=422;e.missingFields=m;throw e}}
export function compactCandidate(c){return{id:c.id,date:c.date,suggestedProcessId:c.suggestedProcessId,importance:c.importance,novelty:c.novelty,thesisImpact:c.thesisImpact,evidenceStrength:c.evidenceStrength,scores:c.scores,content:c.content,analysis:c.analysis,sources:(c.sources||[]).map(s=>({id:s.id,title:s.title,publisher:s.publisher,publishedAt:s.publishedAt,url:s.url,excerpt:s.excerpt,kind:s.kind,role:s.role}))}}
export const compactProcess=p=>p?{id:p.id,domain:p.domain,title:p.title,description:p.description,currentStage:p.currentStage,nextSignals:p.nextSignals}:null;
export function mergeUsage(...u){return u.reduce((t,x)=>({input_tokens:t.input_tokens+Number(x?.inputTokens||x?.input_tokens||0),output_tokens:t.output_tokens+Number(x?.outputTokens||x?.output_tokens||0),input_tokens_details:{cached_tokens:Number(t.input_tokens_details.cached_tokens||0)+Number(x?.cachedInputTokens||x?.input_tokens_details?.cached_tokens||0)}}),{input_tokens:0,output_tokens:0,input_tokens_details:{cached_tokens:0}})}
